### ISSUE TITLE
Exception: unable to retrieve Terminal Propfiles

### ISSUE THREAD

**Issue by lesmo** [paradox00/Flow.Launcher.Plugin.WindowsTerminal#7]
Not entirely sure what changed, but I'd say it was broken from the last Windows Update (KB5027119, KB5027231)? 🤔

```
Flow Launcher version: 1.15.0
OS Version: 22621.1848
IntPtr Length: 8
x64: True

Python Path: C:\Users\lesmo\AppData\Roaming\FlowLauncher\Environments\Python\PythonEmbeddable-v3.8.9\pythonw.exe
Node Path: 
Date: 06/15/2023 10:24:02
Exception:
Windows Terminal profiles Exception: 
Websites: https://github.com/paradox00/Flow.Launcher.Plugin.WindowsTerminal
Author: Aviv B.D.
Version: 0.0.8
Flow.Launcher.Core.ExternalPlugins.FlowPluginException: Traceback (most recent call last):
  File "C:\Users\lesmo\AppData\Roaming\FlowLauncher\Plugins\Windows Terminal profiles-0.0.8\main.py", line 12, in <module>
    TerminalPlugin()
  File "C:\Users\lesmo\AppData\Roaming\FlowLauncher\Plugins\Windows Terminal profiles-0.0.8\plugin\plugin.py", line 19, in __init__
    self.load_settings()
  File "C:\Users\lesmo\AppData\Roaming\FlowLauncher\Plugins\Wi
ndows Terminal profiles-0.0.8\plugin\plugin.py", line 38, in load_settings
    settings = json.load(settings_file)
  File "json\__init__.py", line 293, in load
  File "json\__init__.py", line 357, in loads
  File "json\decoder.py", line 337, in decode
  File "json\decoder.py", line 355, in raw_decode
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

 ---> System.IO.InvalidDataException: Traceback (most recent call last):
  File "C:\Users\lesmo\AppData\Roaming\FlowLauncher\Plugins\Windows Terminal profiles-0.0.8\main.py", line 12, in <module>
    TerminalPlugin()
  File "C:\Users\lesmo\AppData\Roaming\FlowLauncher\Plugins\Windows Terminal profiles-0.0.8\plugin\plugin.py", line 19, in __init__
    self.load_settings()
  File "C:\Users\lesmo\AppData\Roaming\FlowLauncher\Plugins\Windows Terminal profiles-0.0.8\plugin\plugin.py", line 38, in load_settings
    settings = json.load(settings_file)
  File "json\__init__.py", line 293, in load
  File "json\__init__.py", line 357, in loads
  File "json\decoder.py", line 337, in decode
  File "json\decoder.py", line 355, in raw_decode
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

   at Flow.Launcher.Core.Plugin.JsonRPCPlugin.ExecuteAsync(ProcessStartInfo startInfo, CancellationToken token) in C:\projects\flow-launcher\Flow.Launcher.Core\Plugin\JsonRPCPlugin.cs:line 294
   at Flow.Launcher.Core.Plugin.JsonRPCPlugin.ExecuteAsync(ProcessStartInfo startInfo, CancellationToken token) in C:\projects\flow-launcher\Flow.Launcher.Core\Plugin\JsonRPCPlugin.cs:line 299
   at Flow.Launcher.Core.Plugin.JsonRPCPlugin.QueryAsync(Query query, CancellationToken token) in C:\projects\flow-launcher\Flow.Launcher.Core\Plugin\JsonRPCPlugin.cs:line 314
   at Flow.Launcher.Core.Plugin.PluginManager.<>c__DisplayClass22_0.<<QueryForPluginAsync>b__0>d.MoveNext() in C:\projects\flow-launcher\Flow.Launcher.Core\Plugin\PluginManager.cs:line 194
--- End of stack trace from previous location ---
   at Flow.Launcher.Infrastructure.Stopwatch.DebugAsync(String message, Func`1 action) in C:\projects\flow-launcher\Flow.Launcher.Infrastructure\Stopwatch.cs:line 40
   at Flow.Launcher.Core.Plugin.PluginManager.QueryForPluginAsync(PluginPair pair, Query query, CancellationToken token) in C:\projects\flow-launcher\Flow.Launcher.Core\Plugin\PluginManager.cs:line 216
   --- End of inner exception stack trace ---
   at Flow.Launcher.Core.Plugin.PluginManager.QueryForPluginAsync(PluginPair pair, Query query, CancellationToken token) in C:\projects\flow-launcher\Flow.Launcher.Core\Plugin\PluginManager.cs:line 216
   at Flow.Launcher.ViewModel.MainViewModel.<>c__DisplayClass135_0.<<QueryResults>g__QueryTask|2>d.MoveNext() in C:\projects\flow-launcher\Flow.Launcher\ViewModel\MainViewModel.cs:line 836
--- End of stack trace from previous location ---
   at Flow.Launcher.ViewModel.MainViewModel.QueryResults() in C:\projects\flow-launcher\Flow.Launcher\ViewModel\MainViewModel.cs:line 837
   at System.Threading.Tasks.Task.<>c.<ThrowAsync>b__128_0(Object state)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)
```
---
[2023-06-15.txt](https://github.com/paradox00/Flow.Launcher.Plugin.WindowsTerminal/files/11760480/2023-06-15.txt)

**Comment by paradox00** [comment]
should be solved in version 0.0.9 of the plugin.
